-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."killers" add column "is_killed" boolean
--  not null default 'false';
