SET check_function_bodies = false;
INSERT INTO public.actions (id, action) VALUES (3, 'Demander un défaut et qualité de la personne qui t''a invité');
INSERT INTO public.actions (id, action) VALUES (4, 'Affoner la personne');
INSERT INTO public.actions (id, action) VALUES (6, 'Découvrir le kill de la personne');
INSERT INTO public.actions (id, action) VALUES (5, 'Boire dans son verre/Faire boire dans ton verre');
INSERT INTO public.actions (id, action) VALUES (7, 'Faire un shifumi avec la personne');
INSERT INTO public.actions (id, action) VALUES (10, 'Faire répéter une phrase 3 fois');
INSERT INTO public.actions (id, action) VALUES (11, 'Faire chanter un Disney à quelqu''un');
INSERT INTO public.actions (id, action) VALUES (9, 'Se faire servir deux verre');
INSERT INTO public.actions (id, action) VALUES (12, 'Faire dire quelque chose en 3 langues différentes');
INSERT INTO public.actions (id, action) VALUES (13, 'Faire en sorte que la personne essaye de décapsuler de façon originale (pas de décapsuleur/ouvre bouteille ou bac)');
INSERT INTO public.actions (id, action) VALUES (14, 'Faire ranger des vidanges');
INSERT INTO public.actions (id, action) VALUES (15, 'Faire en sorte que la personne te présente un de ses potes');
INSERT INTO public.actions (id, action) VALUES (16, 'Faire en sorte que la personne finisse ta phrase');
INSERT INTO public.actions (id, action) VALUES (17, 'Faire citer un nom de pokemon');
INSERT INTO public.actions (id, action) VALUES (8, 'Faire un selfie (consentant) avec la personne');
INSERT INTO public.actions (id, action) VALUES (18, 'Se faire raconter une blague');
INSERT INTO public.actions (id, action) VALUES (19, 'Obtenir l''aide pour killer quelqu''un (inventer un kill et choisir une personne)');
INSERT INTO public.actions (id, action) VALUES (20, 'Obtenir le plat préférer de la personne');
INSERT INTO public.actions (id, action) VALUES (21, 'Demander à la personne qui elle marie, met dans son lit et tue parmi les organisateurs');
INSERT INTO public.actions (id, action) VALUES (22, 'Faire en sorte que la personne tienne ton verre pendant + de 10 secondes');
INSERT INTO public.actions (id, action) VALUES (24, 'Obtenir le synopsis d''une série');
INSERT INTO public.actions (id, action) VALUES (23, 'Obtenir sa célébrité préféré(e)');
INSERT INTO public.actions (id, action) VALUES (25, 'Dessiner sur la personne avec son consentement ');
INSERT INTO public.actions (id, action) VALUES (26, 'Se faire dessiner dessus par la personne');
INSERT INTO public.actions (id, action) VALUES (27, 'Faire dire par la personne une réplique célèbre (films, ...)');
INSERT INTO public.actions (id, action) VALUES (28, 'Faire prendre une photo de toi avec des potes par la personne');
INSERT INTO public.actions (id, action) VALUES (29, 'Se faire montrer une photo par la personne (sur son téléphone)');
INSERT INTO public.actions (id, action) VALUES (30, 'Avoir la date de naissance de la personne');
INSERT INTO public.actions (id, action) VALUES (31, 'Faire boire un soft/eau à la personne');
INSERT INTO public.actions (id, action) VALUES (32, 'Utiliser le téléphone de la personne pour faire quelque chose (pas juste regarder l''heure)');
SELECT pg_catalog.setval('public.actions_id_seq', 32, true);
